version: "3.7"

networks:
  laravel_app:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'cronus'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'app_user'
      MYSQL_USER: 'app_user'
    volumes:
      - ./_data/mysql:/var/lib/mysql
    networks:
      - laravel_app

  app:
    build:
      args:
        user: dean
        uid: 1001
      context: ./_docker
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      # App
      APP_ENV: 'local'
      APP_NAME: 'cronus'
      APP_VERSION: '1.0.0'
      APP_DEBUG: 'true'
      # Session
      SESSION_DRIVER: 'file'
      SESSION_LIFETIME: '2880'
      # Queue
      QUEUE_DRIVER: 'database'
      # Database
      DB_CONNECTION: 'mysql'
      DB_HOST: 'mysql'
      DB_PORT: '3306'
      DB_DATABASE: 'cronus'
      DB_USERNAME: 'root'
      DB_PASSWORD: 'root'
      # Mail
      MAIL_DRIVER: 'smtp'
      MAIL_HOST: 'smtp.mailtrap.io'
      MAIL_PORT: '2525'
      MAIL_USERNAME: '1234'
      MAIL_PASSWORD: '1234'
      MAIL_ENCRYPTION: 'TLS'
    working_dir: /var/www/
    volumes:
      - .:/var/www
      - ./_docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - laravel_app

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - .:/var/www
      - ./_docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel_app
